version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Build"
  
  build-security:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Build Security"

  test-unit-01:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Test Unit 01"
  
  test-e2e:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Test e2e"
  
  test-services:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Test Services"

  test-unit-00:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Test Unit 00"
  
  ansible:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Ansible"

  deploy-qa:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Deploy QA"

  build-worker:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Build Worker"

  build-app01:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Build App 01"
  
  build-app02:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Build App 02"
  
  migrations:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Migrations"
  
  start-command:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: echo "Start Command"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build-security
      - test-unit-00:
          requires:
            - build
      - test-unit-01:
          requires:
            - build
      - test-services:
          requires:
            - build 
      - test-e2e:
          requires:
            - build
      - ansible:
          requires:
            - test-unit-00
            - test-unit-01
            - test-e2e
            - test-services
            - build-securiti
      - deploy-qa:
          requires:
            - ansible
      - build-worker:
          requires:
            - deploy-qa
      - build-app01:
          requires:
            - deploy-qa
      - build app02:
          requires:
            - deploy-qa
      - migrations:
          requires:
            - build-worker
            - build-app01
            - build-app02
      - start-command:
          requires: 
            - migrations 

































